on: push
name: 🚀 Deploy on preprod
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

        run: ${{ secrets.USER }}

      - name: 📂 Sync all files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.clementprevost.fr
          username: ${{ secrets.USER }}
          password: ${{ secrets.MDP }}