on: push
name: 🚀 Deploy to gestionnairedestock.clementprevost.fr
jobs:
  web-deploy:
    name: 🎉 Deploy start
    runs-on: ubuntu-latest
    environment: FTP

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Composer update
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: 📂 Sync all files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.MDP }}